name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Clojure CLI
      uses: DeLaGuardo/setup-clojure@3.6
      with:
        tools-deps: latest
    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.gitlibs
          .cpcache
        key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Run tests
      run: clojure -T:build test
